services:
  postgres:
    image: postgres:15
    container_name: chattr-postgres
    environment:
      POSTGRES_DB: chattr_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  eureka:
    build:
      context: ../eureka-server
    container_name: chattr-eureka
    ports:
      - "8761:8761"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 10

  user-service:
    build:
      context: ../user-service
    container_name: chattr-user-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chattr_users
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
    depends_on:
      - postgres
        # condition: service_healthy
      - eureka
        # condition: service_healthy

  auth-service:
    build:
      context: ../auth-service
    container_name: chattr-auth-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chattr_users
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      JWT_SECRET: s3NpPZFCfDYWITkl6Vw6cJruGAaaFFHK4SQwKouFm74Ayw2O2vhuanJJYLa/5fH3RZZ0OlW5SUTvzsVoArWZaQ==
    depends_on:
      - postgres
        # condition: service_healthy
      - eureka
        # condition: service_healthy
      - user-service
        # condition: service_started

volumes:
  pgdata: