server:
  port: 8082

spring:
  config:
    import: optional:configserver:
  datasource:
    url: jdbc:postgresql://localhost:5432/chattr_users
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/